version: 2
jobs:
  build:
    working_directory: ~/calismamasam.com

    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          - PGUSER=localhost
          - PGUSER=ubuntu
      - image: circleci/postgres:9.5-alpine
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=calismamasam_test
          - POSTGRES_PASSWORD= ""

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            gem install rspec
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --profile 10 \
                              --out /tmp/test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      # deploy to dokku server
      - deploy:
          name: Deploy to Dokku server
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh-keyscan -H dokku.calismamasam.com >> ~/.ssh/known_hosts
              git remote add dokku dokku@dokku.calismamasam.com:calismamasam
              git push dokku master
            else
              echo "Not master or develop branch so not deploying"
            fi
